import React from 'react';
import { Box } from '@mui/material';

export const Coupons = () => {
  return (
    <Box
      sx={{
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
      }}
    >
      {/*<Typography>This page is under development</Typography>*/}
      <form className='contact-form' id='waitlistForm'>
        <div className='form-header'>
          <h3 className='waitlist-form-title'>Reserve Your Spot</h3>
        </div>

        <div className='form-body'>
          {/* Form will be generated by JavaScript */}
          <div className='form-group'>
            <label htmlFor='name'>
              Full Name <span className='required'>*</span>
            </label>
            <input type='text' id='name' placeholder='Enter your full name' required />
          </div>

          <div className='form-group'>
            <label htmlFor='email'>
              Business Email <span className='required'>*</span>
            </label>
            <input type='email' id='email' placeholder='Enter your work email' required />
          </div>

          <div className='form-group'>
            <label htmlFor='phone'>
              Business Phone <span className='required'>*</span>
            </label>
            <input type='tel' id='phone' placeholder='Enter your work phone' required />
          </div>

          <div className='form-group'>
            <label htmlFor='utmSource'>
              Business source <span className='required'>*</span>
            </label>
            <input type='text' id='utmSource' placeholder='Enter your source' required />
          </div>

          <div className='form-group'>
            <label htmlFor='company'>
              Company <span className='required'>*</span>
            </label>
            <input type='text' id='company' placeholder='Enter your company name' required />
          </div>

          {/* Uncomment below if needed */}
          {/*
    <div className="form-group">
      <label htmlFor="adSpend">
        Monthly Ad Spend <span className="required">*</span>
      </label>
      <select id="adSpend" required defaultValue="">
        <option value="" disabled>Select your monthly ad spend</option>
        <option value="0-5000">$0-$5,000/month</option>
        <option value="5001-10000">$5,001-$10,000/month</option>
        <option value="10001-25000">$10,001-$25,000/month</option>
        <option value="25001-50000">$25,001-$50,000/month</option>
        <option value="50001+">$50,001+/month</option>
      </select>
    </div>

    <div className="form-group checkbox-group">
      <div className="checkbox-container">
        <input type="checkbox" id="requiredConsent" required />
        <label htmlFor="requiredConsent">
          I agree to the processing of my personal data according to the{' '}
          <a href="https://qail.ai/privacy-policy" target="_blank" rel="noopener noreferrer">
            Privacy Policy
          </a>{' '}
          <span className="required">*</span>
        </label>
      </div>
    </div>

    <div className="form-group checkbox-group">
      <div className="checkbox-container">
        <input type="checkbox" id="marketingConsent" />
        <label htmlFor="marketingConsent">
          I agree to receive marketing communications about QAIL AI products and services
        </label>
      </div>
    </div>
    */}

          <div id='formMessage' className='form-message'></div>

          <button type='submit' className='form-submit'>
            Join the Waitlist
          </button>

          <p className='required-note'>
            <span className='required'>*</span> Required fields
          </p>
        </div>
      </form>
    </Box>
  );
};
